// Creating users
POST http://localhost:3000/create-user HTTP/1,1
Accept: */*
Content-Type: application/json

{
    "email": "vini@gmail.com",
    "password": "1234"
}

###
// Getting users
GET http://localhost:3000/users HTTP/1.1
Accept: */*